fgms_special_offers_install:
    path: /install
    defaults:
        _controller: FgmsSpecialOffersBundle:Install:install

fgms_special_offers_auth:
    path: /auth
    defaults:
        _controller: FgmsSpecialOffersBundle:Install:auth

fgms_special_offers_homepage:
    path: /
    defaults: { _controller: FgmsSpecialOffersBundle:Default:index }

fgms_special_offers_create:
    path: /create
    defaults:
        _controller: FgmsSpecialOffersBundle:Default:create

fgms_special_offers_edit:
    path: /edit/{id}
    defaults:
        _controller: FgmsSpecialOffersBundle:Default:edit
    requirements:
        id: "\\d+"

fgms_special_offers_clone:
    path: /clone/{id}
    defaults:
        _controller: FgmsSpecialOffersBundle:Default:clone
    requirements:
        id: "\\d+"

fgms_special_offers_cancel:
    path: /cancel/{id}
    defaults:
        _controller: FgmsSpecialOffersBundle:Default:cancel
    requirements:
        id: "\\d+"
