api_key: 
shared_secret: 
scope: read_content,write_content,read_products,write_products,read_customers,read_orders,read_script_tags,write_script_tags,read_fulfillments,read_themes,write_themes
redirect_url: '/offers/oauth'