services:
    fgms_special_offers.to_https:
        class: Fgms\SpecialOffersBundle\EventListener\ToHttpsListener
        arguments: ["@router"]
        tags:
            -   { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
    fgms_special_offers.email_notifications:
        class: Fgms\SpecialOffersBundle\EventListener\EmailNotificationListener
        arguments: ["%fgms_special_offers.notifications_config%","@swiftmailer.mailer","@twig"]
        tags:
            -   { name: kernel.event_listener, event: specialoffers.started, method: onStart }
            -   { name: kernel.event_listener, event: specialoffers.ended, method: onEnd }
